<!DOCTYPE html>
<?php
  if (!isset($_SESSION)) {
  session_start();
}
 ?>
<html>
  <head>
    <meta charset="utf-8">
    <title>svgg</title>
    <link rel="stylesheet" type="text/css" href="style.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
    <script src="jquery.js"></script>
    <script src="index.js"></script>

  </head>
  <body>
    <main>
      <div class="white">
          <h1> Voici le résultat :</h1>
      </div>

    <div class="ligneFlex">
<a id="retour" href="../index.html"><i class="fas fa-home fa-2x"></i> Retour </a>
    <div class="figure">
    <svg id="svg" width="400" height="400">

      <?php  foreach ($formes as $f) {
           echo $f;  }?>
    </svg>
    </div>
    <br><br>

    <div class="lienFigure">
      <a href="index.html">Ajouter</a>
      <a href="deconnexion.php">Tout effacer</a>
    </div>

  </div>
  </main>
  </body>
</html>
